# Generated by Django 5.0.1 on 2024-01-22 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=35)),
                ('age', models.IntegerField()),
                ('aliases', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='persons/')),
                ('description', models.TextField(max_length=70)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Person Info',
            },
        ),
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=20)),
                ('maker', models.TextField(max_length=15)),
                ('colour', models.TextField(max_length=15)),
                ('image', models.ImageField(upload_to='vehicles/')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intel.personinfo')),
            ],
            options={
                'verbose_name_plural': 'Item Info',
            },
        ),
    ]
